wayland

diff --git a/passgen b/passgen
--- a/passgen
+++ b/passgen
@@ -2,6 +2,42 @@
 # Generate a password and immediately copy it to all clipboards by default
 
 
+which xclip &> /dev/null
+if [ ! $? -eq 0 ]; then
+  XCLIP_FOUND=0
+else
+  XCLIP_FOUND=1
+fi
+which wl-copy &> /dev/null
+if [ ! $? -eq 0 ]; then
+  WLCOPY_FOUND=0
+else
+  WLCOPY_FOUND=1
+fi
+
+if [[ ${WLCOPY_FOUND} -eq 0 && ${XCLIP_FOUND} -eq 0 ]]; then
+  echo 'no copy utility found'
+  exit 1
+fi
+
+if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
+  if [[ ${WLCOPY_FOUND} -eq 0 ]]; then
+    echo 'wl-copy utility not found'
+    exit 1
+  fi
+  COPY_CMD=wl-copy
+elif [ "$XDG_SESSION_TYPE" = "x11" ]; then
+  if [[ ${XCLIP_FOUND} -eq 0 ]]; then
+    echo 'xclip utility not found'
+    exit 1
+  fi
+  COPY_CMD="xclip -i -selection clipboard"
+else
+  echo "Unknown or headless session (Type: $XDG_SESSION_TYPE)"
+  exit 1
+fi
+
+
 # Define what it means to be a long pass
 LONG=63
 
@@ -50,26 +86,26 @@ main() {
   check_cmd pwgen
   check_cmd openssl
 
-	if [[ "$FIRST_ARG" == '-h' || "$FIRST_ARG" == '--help'  ]]; then
-		usage
-		exit 1
-	elif [[ "$FIRST_ARG" == '-l' || "$FIRST_ARG" == '--long'  ]]; then
+  if [[ "$FIRST_ARG" == '-h' || "$FIRST_ARG" == '--help'  ]]; then
+    usage
+    exit 1
+  elif [[ "$FIRST_ARG" == '-l' || "$FIRST_ARG" == '--long'  ]]; then
     longshots
-		exit 1
-	elif [[ "$FIRST_ARG" == '-a' || "$FIRST_ARG" == '--all' || "$FIRST_ARG" == '-v'  ]]; then
+    exit 1
+  elif [[ "$FIRST_ARG" == '-a' || "$FIRST_ARG" == '--all' || "$FIRST_ARG" == '-v'  ]]; then
     obedient
     disobedient
     longshots
-		exit 1
-	elif [[ "$FIRST_ARG" == '-o' || "$FIRST_ARG" == '--obedient'  ]]; then
+    exit 1
+  elif [[ "$FIRST_ARG" == '-o' || "$FIRST_ARG" == '--obedient'  ]]; then
     obedient
-		exit 1
-	elif [[ "$FIRST_ARG" == '-t' || "$FIRST_ARG" == '--test'  ]]; then
+    exit 1
+  elif [[ "$FIRST_ARG" == '-t' || "$FIRST_ARG" == '--test'  ]]; then
     tests
-		exit 1
-	fi
-
-	if [[ "$FIRST_ARG" == '-u' || "$FIRST_ARG" == '--unsafe'  ]]; then
+    exit 1
+  fi
+  
+  if [[ "$FIRST_ARG" == '-u' || "$FIRST_ARG" == '--unsafe'  ]]; then
     if [[ $2 =~ $re ]] ; then
       PASS_LENGTH=$2
     else
@@ -78,24 +114,23 @@ main() {
     unsafe
   else
     shuffy
-	fi
+  fi
 
   clippy
-
 }
 
 # Help
 usage() {
-	echo -e "Passgen - The CLI Password Generator"
-	echo "Usage:"
-	echo -e "passgen\t\t-      by default will generate a password with lots of chars
+  echo -e "Passgen - The CLI Password Generator"
+  echo "Usage:"
+  echo -e "passgen\t\t-      by default will generate a password with lots of chars
  use a pretty good random and copy to your clipboard, primary and
 secondary.i.e. ctrl-shift-v, shift-insert, and middle click all ought to
 work in linux and print you out a decent password."
-	echo -e "passgen -o\t- generate obedient passwords"
-	echo -e "passgen -a\t- generate all passwords"
-	echo -e "passgen -l\t- generate long hash passwords"
-	echo -e "passgen 12\t- generate 12 character passwords"
+  echo -e "passgen -o\t- generate obedient passwords"
+  echo -e "passgen -a\t- generate all passwords"
+  echo -e "passgen -l\t- generate long hash passwords"
+  echo -e "passgen 12\t- generate 12 character passwords"
 }
 
 # Main block of random generators these all obey PASS_LENGTH
@@ -104,9 +139,21 @@ obedient() {
 }
 
 clippy () {
-  echo -n $RESULT | xclip -i  -selection clipboard
-  echo -n $RESULT | xclip -i  -selection primary
-  echo -n $RESULT | xclip -i  -selection secondary
+  if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
+    if [[ ${WLCOPY_FOUND} -eq 1 ]]; then
+      echo -n $RESULT | wl-copy --primary
+      echo -n $RESULT | wl-copy
+    fi
+  elif [ "$XDG_SESSION_TYPE" = "x11" ]; then
+    if [[ ${XCLIP_FOUND} -eq 1 ]]; then
+      echo -n $RESULT | xclip -i  -selection clipboard
+      echo -n $RESULT | xclip -i  -selection primary
+      echo -n $RESULT | xclip -i  -selection secondary
+    fi
+  else
+    echo "Unknown or headless session (Type: $XDG_SESSION_TYPE)"
+    exit 1
+  fi
   echo $RESULT
 }
 
